services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: citespine
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d citespine"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PG_DSN: "postgresql+psycopg://postgres:postgres@postgres:5432/citespine"
      VECTOR_BACKEND: "pgvector"
      LLM_PROVIDER: "ollama"
      EMBEDDINGS_PROVIDER: "local"
      AS_OF_DEFAULT: "2023-12-31"
      TOP_K: "10"
      CHUNK_SIZE: "900"
      CHUNK_OVERLAP: "150"
      INVITE_TOKEN: "letmein"
      OFFLINE: "true"
      DEMO_MODE: "true"
      DEMO_RATE_LIMIT_PER_IP: "100/hour"
    volumes:
      - ./:/app
    ports: ["8000:8000"]
    depends_on:
      postgres:
        condition: service_healthy

  k6:
    image: grafana/k6:latest
    profiles: ["perf"]
    depends_on: [api]
    networks: ["default"]
    working_dir: /work
    environment:
      - K6_API_KEY=${K6_API_KEY}
    volumes:
      - ./:/work

volumes:
  pgdata:
